title: The Gluten Free Hackers Collective
description: A group of humans trying to hack computers, and yeet that wheat.
theme: just-the-docs

url: https://glutenfreehackerscollective.org

# Logo in browser tab
favicon_ico: "/assets/images/transparent_logo.png"

# Ow, my eyes!!
color_scheme: dark

# Enable or disable the side/mobile menu globally
nav_enabled: true


# Logo on home page
logo: "/assets/images/transparent_logo_name.png"
