title: The Gluten Free Hackers Collective
description: A group of humans trying to hack computers, and yeet that wheat.
theme: just-the-docs

url: https://glutenfreehackerscollective.org

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
