title: The Gluten Free Hackers Collective
description: A group of humans trying to hack computers, and yeet that wheat.
theme: just-the-docs

url: https://glutenfreehackerscollective.org

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Logo in browser tab
favicon_ico: "/assets/images/logo.jpg"

# Ow, my eyes!!
color_scheme: dark

# Enable or disable the side/mobile menu globally
nav_enabled: true


# Logo on home page
logo: "/assets/images/logo_name.jpg"